# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.group_membership import GroupMembership
from openapi_server import util

from openapi_server.models.group_membership import GroupMembership  # noqa: E501

class GroupsIdMembershipsGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, group_memberships=None):  # noqa: E501
        """GroupsIdMembershipsGet200Response - a model defined in OpenAPI

        :param group_memberships: The group_memberships of this GroupsIdMembershipsGet200Response.  # noqa: E501
        :type group_memberships: List[GroupMembership]
        """
        self.openapi_types = {
            'group_memberships': List[GroupMembership]
        }

        self.attribute_map = {
            'group_memberships': 'GroupMemberships'
        }

        self._group_memberships = group_memberships

    @classmethod
    def from_dict(cls, dikt) -> 'GroupsIdMembershipsGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _groups__id__memberships_get_200_response of this GroupsIdMembershipsGet200Response.  # noqa: E501
        :rtype: GroupsIdMembershipsGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_memberships(self):
        """Gets the group_memberships of this GroupsIdMembershipsGet200Response.


        :return: The group_memberships of this GroupsIdMembershipsGet200Response.
        :rtype: List[GroupMembership]
        """
        return self._group_memberships

    @group_memberships.setter
    def group_memberships(self, group_memberships):
        """Sets the group_memberships of this GroupsIdMembershipsGet200Response.


        :param group_memberships: The group_memberships of this GroupsIdMembershipsGet200Response.
        :type group_memberships: List[GroupMembership]
        """

        self._group_memberships = group_memberships
