# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class GroupAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, create_date=None, last_update_date=None, owner=None):  # noqa: E501
        """GroupAllOf - a model defined in OpenAPI

        :param id: The id of this GroupAllOf.  # noqa: E501
        :type id: str
        :param create_date: The create_date of this GroupAllOf.  # noqa: E501
        :type create_date: datetime
        :param last_update_date: The last_update_date of this GroupAllOf.  # noqa: E501
        :type last_update_date: datetime
        :param owner: The owner of this GroupAllOf.  # noqa: E501
        :type owner: str
        """
        self.openapi_types = {
            'id': str,
            'create_date': datetime,
            'last_update_date': datetime,
            'owner': str
        }

        self.attribute_map = {
            'id': 'id',
            'create_date': 'createDate',
            'last_update_date': 'lastUpdateDate',
            'owner': 'owner'
        }

        self._id = id
        self._create_date = create_date
        self._last_update_date = last_update_date
        self._owner = owner

    @classmethod
    def from_dict(cls, dikt) -> 'GroupAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The group_allOf of this GroupAllOf.  # noqa: E501
        :rtype: GroupAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this GroupAllOf.

        the id of a group. this is a uuid with the prefix \"group-\".   # noqa: E501

        :return: The id of this GroupAllOf.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GroupAllOf.

        the id of a group. this is a uuid with the prefix \"group-\".   # noqa: E501

        :param id: The id of this GroupAllOf.
        :type id: str
        """
        if id is not None and not re.search(r'^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', id):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/`")  # noqa: E501

        self._id = id

    @property
    def create_date(self):
        """Gets the create_date of this GroupAllOf.

        the date and time the group was created.  # noqa: E501

        :return: The create_date of this GroupAllOf.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this GroupAllOf.

        the date and time the group was created.  # noqa: E501

        :param create_date: The create_date of this GroupAllOf.
        :type create_date: datetime
        """

        self._create_date = create_date

    @property
    def last_update_date(self):
        """Gets the last_update_date of this GroupAllOf.

        the date and time the group was last updated.  # noqa: E501

        :return: The last_update_date of this GroupAllOf.
        :rtype: datetime
        """
        return self._last_update_date

    @last_update_date.setter
    def last_update_date(self, last_update_date):
        """Sets the last_update_date of this GroupAllOf.

        the date and time the group was last updated.  # noqa: E501

        :param last_update_date: The last_update_date of this GroupAllOf.
        :type last_update_date: datetime
        """

        self._last_update_date = last_update_date

    @property
    def owner(self):
        """Gets the owner of this GroupAllOf.

        id of a user. this is a uuid with the prefix \"user-\".   # noqa: E501

        :return: The owner of this GroupAllOf.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this GroupAllOf.

        id of a user. this is a uuid with the prefix \"user-\".   # noqa: E501

        :param owner: The owner of this GroupAllOf.
        :type owner: str
        """

        self._owner = owner
