# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class Group(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, created_by=None, id=None, create_date=None, last_update_date=None, owner=None, memberships=None):  # noqa: E501
        """Group - a model defined in OpenAPI

        :param name: The name of this Group.  # noqa: E501
        :type name: str
        :param created_by: The created_by of this Group.  # noqa: E501
        :type created_by: str
        :param id: The id of this Group.  # noqa: E501
        :type id: str
        :param create_date: The create_date of this Group.  # noqa: E501
        :type create_date: datetime
        :param last_update_date: The last_update_date of this Group.  # noqa: E501
        :type last_update_date: datetime
        :param owner: The owner of this Group.  # noqa: E501
        :type owner: str
        :param memberships: The memberships of this Group.  # noqa: E501
        :type memberships: List[str]
        """
        self.openapi_types = {
            'name': str,
            'created_by': str,
            'id': str,
            'create_date': datetime,
            'last_update_date': datetime,
            'owner': str,
            'memberships': List[str]
        }

        self.attribute_map = {
            'name': 'name',
            'created_by': 'createdBy',
            'id': 'id',
            'create_date': 'createDate',
            'last_update_date': 'lastUpdateDate',
            'owner': 'owner',
            'memberships': 'memberships'
        }

        self._name = name
        self._created_by = created_by
        self._id = id
        self._create_date = create_date
        self._last_update_date = last_update_date
        self._owner = owner
        self._memberships = memberships

    @classmethod
    def from_dict(cls, dikt) -> 'Group':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The group of this Group.  # noqa: E501
        :rtype: Group
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Group.

        the name of the group.  # noqa: E501

        :return: The name of this Group.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Group.

        the name of the group.  # noqa: E501

        :param name: The name of this Group.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def created_by(self):
        """Gets the created_by of this Group.

        id of a user. this is a uuid with the prefix \"user-\".   # noqa: E501

        :return: The created_by of this Group.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Group.

        id of a user. this is a uuid with the prefix \"user-\".   # noqa: E501

        :param created_by: The created_by of this Group.
        :type created_by: str
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501
        if created_by is not None and not re.search(r'^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', created_by):  # noqa: E501
            raise ValueError("Invalid value for `created_by`, must be a follow pattern or equal to `/^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/`")  # noqa: E501

        self._created_by = created_by

    @property
    def id(self):
        """Gets the id of this Group.

        the id of a group. this is a uuid with the prefix \"group-\".   # noqa: E501

        :return: The id of this Group.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Group.

        the id of a group. this is a uuid with the prefix \"group-\".   # noqa: E501

        :param id: The id of this Group.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and not re.search(r'^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', id):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/`")  # noqa: E501

        self._id = id

    @property
    def create_date(self):
        """Gets the create_date of this Group.

        the date and time the group was created.  # noqa: E501

        :return: The create_date of this Group.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this Group.

        the date and time the group was created.  # noqa: E501

        :param create_date: The create_date of this Group.
        :type create_date: datetime
        """
        if create_date is None:
            raise ValueError("Invalid value for `create_date`, must not be `None`")  # noqa: E501

        self._create_date = create_date

    @property
    def last_update_date(self):
        """Gets the last_update_date of this Group.

        the date and time the group was last updated.  # noqa: E501

        :return: The last_update_date of this Group.
        :rtype: datetime
        """
        return self._last_update_date

    @last_update_date.setter
    def last_update_date(self, last_update_date):
        """Sets the last_update_date of this Group.

        the date and time the group was last updated.  # noqa: E501

        :param last_update_date: The last_update_date of this Group.
        :type last_update_date: datetime
        """
        if last_update_date is None:
            raise ValueError("Invalid value for `last_update_date`, must not be `None`")  # noqa: E501

        self._last_update_date = last_update_date

    @property
    def owner(self):
        """Gets the owner of this Group.

        id of a user. this is a uuid with the prefix \"user-\".   # noqa: E501

        :return: The owner of this Group.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Group.

        id of a user. this is a uuid with the prefix \"user-\".   # noqa: E501

        :param owner: The owner of this Group.
        :type owner: str
        """
        if owner is None:
            raise ValueError("Invalid value for `owner`, must not be `None`")  # noqa: E501
        if owner is not None and not re.search(r'^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', owner):  # noqa: E501
            raise ValueError("Invalid value for `owner`, must be a follow pattern or equal to `/^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/`")  # noqa: E501

        self._owner = owner

    @property
    def memberships(self):
        """Gets the memberships of this Group.

        the ids of the group memberships.  # noqa: E501

        :return: The memberships of this Group.
        :rtype: List[str]
        """
        return self._memberships

    @memberships.setter
    def memberships(self, memberships):
        """Sets the memberships of this Group.

        the ids of the group memberships.  # noqa: E501

        :param memberships: The memberships of this Group.
        :type memberships: List[str]
        """
        if memberships is None:
            raise ValueError("Invalid value for `memberships`, must not be `None`")  # noqa: E501

        self._memberships = memberships
