# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.group_membership import GroupMembership
from openapi_server import util

from openapi_server.models.group_membership import GroupMembership  # noqa: E501

class GroupsIdMembershipsPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, group_membership=None):  # noqa: E501
        """GroupsIdMembershipsPost201Response - a model defined in OpenAPI

        :param group_membership: The group_membership of this GroupsIdMembershipsPost201Response.  # noqa: E501
        :type group_membership: GroupMembership
        """
        self.openapi_types = {
            'group_membership': GroupMembership
        }

        self.attribute_map = {
            'group_membership': 'GroupMembership'
        }

        self._group_membership = group_membership

    @classmethod
    def from_dict(cls, dikt) -> 'GroupsIdMembershipsPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _groups__id__memberships_post_201_response of this GroupsIdMembershipsPost201Response.  # noqa: E501
        :rtype: GroupsIdMembershipsPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_membership(self):
        """Gets the group_membership of this GroupsIdMembershipsPost201Response.


        :return: The group_membership of this GroupsIdMembershipsPost201Response.
        :rtype: GroupMembership
        """
        return self._group_membership

    @group_membership.setter
    def group_membership(self, group_membership):
        """Sets the group_membership of this GroupsIdMembershipsPost201Response.


        :param group_membership: The group_membership of this GroupsIdMembershipsPost201Response.
        :type group_membership: GroupMembership
        """

        self._group_membership = group_membership
