# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.group import Group
from openapi_server import util

from openapi_server.models.group import Group  # noqa: E501

class GroupsGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, groups=None):  # noqa: E501
        """GroupsGet200Response - a model defined in OpenAPI

        :param groups: The groups of this GroupsGet200Response.  # noqa: E501
        :type groups: List[Group]
        """
        self.openapi_types = {
            'groups': List[Group]
        }

        self.attribute_map = {
            'groups': 'Groups'
        }

        self._groups = groups

    @classmethod
    def from_dict(cls, dikt) -> 'GroupsGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _groups_get_200_response of this GroupsGet200Response.  # noqa: E501
        :rtype: GroupsGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def groups(self):
        """Gets the groups of this GroupsGet200Response.


        :return: The groups of this GroupsGet200Response.
        :rtype: List[Group]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this GroupsGet200Response.


        :param groups: The groups of this GroupsGet200Response.
        :type groups: List[Group]
        """

        self._groups = groups
