# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.item import Item
from openapi_server import util

from openapi_server.models.item import Item  # noqa: E501

class ItemsGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """ItemsGet200Response - a model defined in OpenAPI

        :param items: The items of this ItemsGet200Response.  # noqa: E501
        :type items: Item
        """
        self.openapi_types = {
            'items': Item
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'ItemsGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _items_get_200_response of this ItemsGet200Response.  # noqa: E501
        :rtype: ItemsGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this ItemsGet200Response.


        :return: The items of this ItemsGet200Response.
        :rtype: Item
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this ItemsGet200Response.


        :param items: The items of this ItemsGet200Response.
        :type items: Item
        """

        self._items = items
