# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class ItemAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, create_date=None, last_update_date=None, created_by=None):  # noqa: E501
        """ItemAllOf - a model defined in OpenAPI

        :param id: The id of this ItemAllOf.  # noqa: E501
        :type id: str
        :param create_date: The create_date of this ItemAllOf.  # noqa: E501
        :type create_date: datetime
        :param last_update_date: The last_update_date of this ItemAllOf.  # noqa: E501
        :type last_update_date: datetime
        :param created_by: The created_by of this ItemAllOf.  # noqa: E501
        :type created_by: str
        """
        self.openapi_types = {
            'id': str,
            'create_date': datetime,
            'last_update_date': datetime,
            'created_by': str
        }

        self.attribute_map = {
            'id': 'id',
            'create_date': 'createDate',
            'last_update_date': 'lastUpdateDate',
            'created_by': 'createdBy'
        }

        self._id = id
        self._create_date = create_date
        self._last_update_date = last_update_date
        self._created_by = created_by

    @classmethod
    def from_dict(cls, dikt) -> 'ItemAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The item_allOf of this ItemAllOf.  # noqa: E501
        :rtype: ItemAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ItemAllOf.

        the id of the item. this is a uuid with a prefix of \"item-\".   # noqa: E501

        :return: The id of this ItemAllOf.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ItemAllOf.

        the id of the item. this is a uuid with a prefix of \"item-\".   # noqa: E501

        :param id: The id of this ItemAllOf.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and not re.search(r'^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', id):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/`")  # noqa: E501

        self._id = id

    @property
    def create_date(self):
        """Gets the create_date of this ItemAllOf.

        the date and time the item was created.  # noqa: E501

        :return: The create_date of this ItemAllOf.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this ItemAllOf.

        the date and time the item was created.  # noqa: E501

        :param create_date: The create_date of this ItemAllOf.
        :type create_date: datetime
        """
        if create_date is None:
            raise ValueError("Invalid value for `create_date`, must not be `None`")  # noqa: E501

        self._create_date = create_date

    @property
    def last_update_date(self):
        """Gets the last_update_date of this ItemAllOf.

        the date and time the item was last updated.  # noqa: E501

        :return: The last_update_date of this ItemAllOf.
        :rtype: datetime
        """
        return self._last_update_date

    @last_update_date.setter
    def last_update_date(self, last_update_date):
        """Sets the last_update_date of this ItemAllOf.

        the date and time the item was last updated.  # noqa: E501

        :param last_update_date: The last_update_date of this ItemAllOf.
        :type last_update_date: datetime
        """
        if last_update_date is None:
            raise ValueError("Invalid value for `last_update_date`, must not be `None`")  # noqa: E501

        self._last_update_date = last_update_date

    @property
    def created_by(self):
        """Gets the created_by of this ItemAllOf.

        id of a user. This is just a string, since the user id is provided by the authentication provider. (in this case, auth0)   # noqa: E501

        :return: The created_by of this ItemAllOf.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ItemAllOf.

        id of a user. This is just a string, since the user id is provided by the authentication provider. (in this case, auth0)   # noqa: E501

        :param created_by: The created_by of this ItemAllOf.
        :type created_by: str
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by
