# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.update_item import UpdateItem
from openapi_server import util

from openapi_server.models.update_item import UpdateItem  # noqa: E501

class ItemsIdPut200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, room=None):  # noqa: E501
        """ItemsIdPut200Response - a model defined in OpenAPI

        :param room: The room of this ItemsIdPut200Response.  # noqa: E501
        :type room: UpdateItem
        """
        self.openapi_types = {
            'room': UpdateItem
        }

        self.attribute_map = {
            'room': 'Room'
        }

        self._room = room

    @classmethod
    def from_dict(cls, dikt) -> 'ItemsIdPut200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _items__id__put_200_response of this ItemsIdPut200Response.  # noqa: E501
        :rtype: ItemsIdPut200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self):
        """Gets the room of this ItemsIdPut200Response.


        :return: The room of this ItemsIdPut200Response.
        :rtype: UpdateItem
        """
        return self._room

    @room.setter
    def room(self, room):
        """Sets the room of this ItemsIdPut200Response.


        :param room: The room of this ItemsIdPut200Response.
        :type room: UpdateItem
        """

        self._room = room
