# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class NewUnavailability(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item=None, startDate=None, endDate=None, type=None):  # noqa: E501
        """NewUnavailability - a model defined in OpenAPI

        :param item: The item of this NewUnavailability.  # noqa: E501
        :type item: str
        :param startDate: The startDate of this NewUnavailability.  # noqa: E501
        :type startDate: str
        :param endDate: The endDate of this NewUnavailability.  # noqa: E501
        :type endDate: str
        :param type: The type of this NewUnavailability.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'item': str,
            'startDate': str,
            'endDate': str,
            'type': str
        }

        self.attribute_map = {
            'item': 'item',
            'startDate': 'startDate',
            'endDate': 'endDate',
            'type': 'type'
        }

        self._item = item
        self._startdatetime = startDate
        self._enddatetime = endDate
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'NewUnavailability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newUnavailability of this NewUnavailability.  # noqa: E501
        :rtype: NewUnavailability
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item(self):
        """Gets the item of this NewUnavailability.

        the id of the item. this is a uuid with a prefix of \"item-\".   # noqa: E501

        :return: The item of this NewUnavailability.
        :rtype: str
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this NewUnavailability.

        the id of the item. this is a uuid with a prefix of \"item-\".   # noqa: E501

        :param item: The item of this NewUnavailability.
        :type item: str
        """
        if item is None:
            raise ValueError("Invalid value for `item`, must not be `None`")  # noqa: E501
        if item is not None and not re.search(r'^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', item):  # noqa: E501
            raise ValueError("Invalid value for `item`, must be a follow pattern or equal to `/^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/`")  # noqa: E501

        self._item = item

    @property
    def startDate(self):
        """Gets the startDate of this NewUnavailability.

        date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00  # noqa: E501

        :return: The startDate of this NewUnavailability.
        :rtype: str
        """
        return self._startdatetime

    @startDate.setter
    def startDate(self, startDate):
        """Sets the startDate of this NewUnavailability.

        date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00  # noqa: E501

        :param startDate: The startDate of this NewUnavailability.
        :type startDate: str
        """
        if startDate is None:
            raise ValueError("Invalid value for `startDate`, must not be `None`")  # noqa: E501
        if startDate is not None and not re.search(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}t([01][0-9]|2[0-3]):(00|15|30|45):00$', startDate):  # noqa: E501
            raise ValueError("Invalid value for `startDate`, must be a follow pattern or equal to `/^[0-9]{4}-[0-9]{2}-[0-9]{2}t([01][0-9]|2[0-3]):(00|15|30|45):00$/`")  # noqa: E501

        self._startdatetime = startDate

    @property
    def endDate(self):
        """Gets the endDate of this NewUnavailability.

        date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00  # noqa: E501

        :return: The endDate of this NewUnavailability.
        :rtype: str
        """
        return self._enddatetime

    @endDate.setter
    def endDate(self, endDate):
        """Sets the endDate of this NewUnavailability.

        date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00  # noqa: E501

        :param endDate: The endDate of this NewUnavailability.
        :type endDate: str
        """
        if endDate is None:
            raise ValueError("Invalid value for `endDate`, must not be `None`")  # noqa: E501
        if endDate is not None and not re.search(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}t([01][0-9]|2[0-3]):(00|15|30|45):00$', endDate):  # noqa: E501
            raise ValueError("Invalid value for `endDate`, must be a follow pattern or equal to `/^[0-9]{4}-[0-9]{2}-[0-9]{2}t([01][0-9]|2[0-3]):(00|15|30|45):00$/`")  # noqa: E501

        self._enddatetime = endDate

    @property
    def type(self):
        """Gets the type of this NewUnavailability.


        :return: The type of this NewUnavailability.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this NewUnavailability.


        :param type: The type of this NewUnavailability.
        :type type: str
        """
        allowed_values = ["maintenance", "booking", "off_hours", "other"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
