# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class Unavailability(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item=None, startDate=None, endDate=None, type=None, id=None, create_date=None, last_updated_date=None):  # noqa: E501
        """Unavailability - a model defined in OpenAPI

        :param item: The item of this Unavailability.  # noqa: E501
        :type item: str
        :param startDate: The startDate of this Unavailability.  # noqa: E501
        :type startDate: str
        :param endDate: The endDate of this Unavailability.  # noqa: E501
        :type endDate: str
        :param type: The type of this Unavailability.  # noqa: E501
        :type type: str
        :param id: The id of this Unavailability.  # noqa: E501
        :type id: str
        :param create_date: The create_date of this Unavailability.  # noqa: E501
        :type create_date: datetime
        :param last_updated_date: The last_updated_date of this Unavailability.  # noqa: E501
        :type last_updated_date: datetime
        """
        self.openapi_types = {
            'item': str,
            'startDate': str,
            'endDate': str,
            'type': str,
            'id': str,
            'create_date': datetime,
            'last_updated_date': datetime
        }

        self.attribute_map = {
            'item': 'item',
            'startDate': 'startDate',
            'endDate': 'endDate',
            'type': 'type',
            'id': 'id',
            'create_date': 'createDate',
            'last_updated_date': 'lastUpdatedDate'
        }

        self._item = item
        self._startdatetime = startDate
        self._enddatetime = endDate
        self._type = type
        self._id = id
        self._create_date = create_date
        self._last_updated_date = last_updated_date

    @classmethod
    def from_dict(cls, dikt) -> 'Unavailability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The unavailability of this Unavailability.  # noqa: E501
        :rtype: Unavailability
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item(self):
        """Gets the item of this Unavailability.

        the id of the item. this is a uuid with a prefix of \"item-\".   # noqa: E501

        :return: The item of this Unavailability.
        :rtype: str
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this Unavailability.

        the id of the item. this is a uuid with a prefix of \"item-\".   # noqa: E501

        :param item: The item of this Unavailability.
        :type item: str
        """
        if item is None:
            raise ValueError("Invalid value for `item`, must not be `None`")  # noqa: E501
        if item is not None and not re.search(r'^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', item):  # noqa: E501
            raise ValueError("Invalid value for `item`, must be a follow pattern or equal to `/^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/`")  # noqa: E501

        self._item = item

    @property
    def startDate(self):
        """Gets the startDate of this Unavailability.

        date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00  # noqa: E501

        :return: The startDate of this Unavailability.
        :rtype: str
        """
        return self._startdatetime

    @startDate.setter
    def startDate(self, startDate):
        """Sets the startDate of this Unavailability.

        date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00  # noqa: E501

        :param startDate: The startDate of this Unavailability.
        :type startDate: str
        """
        if startDate is None:
            raise ValueError("Invalid value for `startDate`, must not be `None`")  # noqa: E501
        if startDate is not None and not re.search(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}t([01][0-9]|2[0-3]):(00|15|30|45):00$', startDate):  # noqa: E501
            raise ValueError("Invalid value for `startDate`, must be a follow pattern or equal to `/^[0-9]{4}-[0-9]{2}-[0-9]{2}t([01][0-9]|2[0-3]):(00|15|30|45):00$/`")  # noqa: E501

        self._startdatetime = startDate

    @property
    def endDate(self):
        """Gets the endDate of this Unavailability.

        date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00  # noqa: E501

        :return: The endDate of this Unavailability.
        :rtype: str
        """
        return self._enddatetime

    @endDate.setter
    def endDate(self, endDate):
        """Sets the endDate of this Unavailability.

        date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00  # noqa: E501

        :param endDate: The endDate of this Unavailability.
        :type endDate: str
        """
        if endDate is None:
            raise ValueError("Invalid value for `endDate`, must not be `None`")  # noqa: E501
        if endDate is not None and not re.search(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}t([01][0-9]|2[0-3]):(00|15|30|45):00$', endDate):  # noqa: E501
            raise ValueError("Invalid value for `endDate`, must be a follow pattern or equal to `/^[0-9]{4}-[0-9]{2}-[0-9]{2}t([01][0-9]|2[0-3]):(00|15|30|45):00$/`")  # noqa: E501

        self._enddatetime = endDate

    @property
    def type(self):
        """Gets the type of this Unavailability.


        :return: The type of this Unavailability.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Unavailability.


        :param type: The type of this Unavailability.
        :type type: str
        """
        allowed_values = ["maintenance", "booking", "off_hours", "other"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def id(self):
        """Gets the id of this Unavailability.

        the id of an unavailability. this is a uuid with the prefix \"unavailability-\".   # noqa: E501

        :return: The id of this Unavailability.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Unavailability.

        the id of an unavailability. this is a uuid with the prefix \"unavailability-\".   # noqa: E501

        :param id: The id of this Unavailability.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and not re.search(r'^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', id):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/`")  # noqa: E501

        self._id = id

    @property
    def create_date(self):
        """Gets the create_date of this Unavailability.

        the date and time the unavailability was created.  # noqa: E501

        :return: The create_date of this Unavailability.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this Unavailability.

        the date and time the unavailability was created.  # noqa: E501

        :param create_date: The create_date of this Unavailability.
        :type create_date: datetime
        """
        if create_date is None:
            raise ValueError("Invalid value for `create_date`, must not be `None`")  # noqa: E501

        self._create_date = create_date

    @property
    def last_updated_date(self):
        """Gets the last_updated_date of this Unavailability.

        the date and time the unavailability was last updated.  # noqa: E501

        :return: The last_updated_date of this Unavailability.
        :rtype: datetime
        """
        return self._last_updated_date

    @last_updated_date.setter
    def last_updated_date(self, last_updated_date):
        """Sets the last_updated_date of this Unavailability.

        the date and time the unavailability was last updated.  # noqa: E501

        :param last_updated_date: The last_updated_date of this Unavailability.
        :type last_updated_date: datetime
        """
        if last_updated_date is None:
            raise ValueError("Invalid value for `last_updated_date`, must not be `None`")  # noqa: E501

        self._last_updated_date = last_updated_date
