# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.authorization import Authorization


class AuthenticationLoginPost201Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AuthenticationLoginPost201Response - a model defined in OpenAPI

        authorization: The authorization of this AuthenticationLoginPost201Response [Optional].
    """

    authorization: Optional[Authorization] = Field(alias="authorization", default=None)

AuthenticationLoginPost201Response.update_forward_refs()
