# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Authorization(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Authorization - a model defined in OpenAPI

        access_token: The access_token of this Authorization [Optional].
        expires_at: The expires_at of this Authorization [Optional].
    """

    access_token: Optional[str] = Field(alias="accessToken", default=None)
    expires_at: Optional[datetime] = Field(alias="expiresAt", default=None)

Authorization.update_forward_refs()
