# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class UsernamePasswordPair(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UsernamePasswordPair - a model defined in OpenAPI

        client_id: The client_id of this UsernamePasswordPair [Optional].
        username: The username of this UsernamePasswordPair [Optional].
        password: The password of this UsernamePasswordPair [Optional].
    """

    client_id: Optional[str] = Field(alias="clientId", default=None)
    username: Optional[str] = Field(alias="username", default=None)
    password: Optional[str] = Field(alias="password", default=None)

    @validator("client_id")
    def client_id_pattern(cls, value):
        assert value is not None and re.match(r"^[^\s]*$", value)
        return value

    @validator("username")
    def username_pattern(cls, value):
        assert value is not None and re.match(r"^[^\s]*$", value)
        return value

UsernamePasswordPair.update_forward_refs()
