# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.user import User
from openapi_server import util

from openapi_server.models.user import User  # noqa: E501

class GroupsIdUsersGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, users=None):  # noqa: E501
        """GroupsIdUsersGet200Response - a model defined in OpenAPI

        :param users: The users of this GroupsIdUsersGet200Response.  # noqa: E501
        :type users: List[User]
        """
        self.openapi_types = {
            'users': List[User]
        }

        self.attribute_map = {
            'users': 'users'
        }

        self._users = users

    @classmethod
    def from_dict(cls, dikt) -> 'GroupsIdUsersGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _groups__id__users_get_200_response of this GroupsIdUsersGet200Response.  # noqa: E501
        :rtype: GroupsIdUsersGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def users(self):
        """Gets the users of this GroupsIdUsersGet200Response.


        :return: The users of this GroupsIdUsersGet200Response.
        :rtype: List[User]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this GroupsIdUsersGet200Response.


        :param users: The users of this GroupsIdUsersGet200Response.
        :type users: List[User]
        """

        self._users = users
