# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.update_item import UpdateItem


class ItemsIdPut200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ItemsIdPut200Response - a model defined in OpenAPI

        room: The room of this ItemsIdPut200Response [Optional].
    """

    room: Optional[UpdateItem] = Field(alias="Room", default=None)

ItemsIdPut200Response.update_forward_refs()
