# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class NewUser(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NewUser - a model defined in OpenAPI

        username: The username of this NewUser.
        email: The email of this NewUser.
        password: The password of this NewUser.
        role: The role of this NewUser.
    """

    username: str = Field(alias="username")
    email: EmailStr = Field(alias="email")
    password: str = Field(alias="password")
    role: str = Field(alias="role")

NewUser.update_forward_refs()
