# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class UpdateUser(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UpdateUser - a model defined in OpenAPI

        username: The username of this UpdateUser [Optional].
        email: The email of this UpdateUser [Optional].
        password: The password of this UpdateUser [Optional].
    """

    username: Optional[str] = Field(alias="username", default=None)
    email: Optional[EmailStr] = Field(alias="email", default=None)
    password: Optional[str] = Field(alias="password", default=None)

UpdateUser.update_forward_refs()
