# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class User(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    User - a model defined in OpenAPI

        username: The username of this User.
        email: The email of this User.
        password: The password of this User.
        role: The role of this User.
        id: The id of this User.
        created_at: The created_at of this User.
        last_updated_at: The last_updated_at of this User.
    """

    username: str = Field(alias="username")
    email: EmailStr = Field(alias="email")
    password: str = Field(alias="password")
    role: str = Field(alias="role")
    id: str = Field(alias="id")
    created_at: datetime = Field(alias="createdAt")
    last_updated_at: datetime = Field(alias="lastUpdatedAt")

    @validator("id")
    def id_pattern(cls, value):
        assert value is not None and re.match(r"^[a-z]+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", value)
        return value

User.update_forward_refs()
