/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemAllOf
 */
export interface ItemAllOf {
    /**
     * the id of the item. this is a uuid with a prefix of "item-".
     * @type {string}
     * @memberof ItemAllOf
     */
    id: string;
    /**
     * the date and time the item was created.
     * @type {Date}
     * @memberof ItemAllOf
     */
    readonly createDate: Date;
    /**
     * the date and time the item was last updated.
     * @type {Date}
     * @memberof ItemAllOf
     */
    readonly lastUpdateDate: Date;
    /**
     * id of a user. this is a uuid with the prefix "user-".
     * @type {string}
     * @memberof ItemAllOf
     */
    createdBy: string;
}

/**
 * Check if a given object implements the ItemAllOf interface.
 */
export function instanceOfItemAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createDate" in value;
    isInstance = isInstance && "lastUpdateDate" in value;
    isInstance = isInstance && "createdBy" in value;

    return isInstance;
}

export function ItemAllOfFromJSON(json: any): ItemAllOf {
    return ItemAllOfFromJSONTyped(json, false);
}

export function ItemAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createDate': (new Date(json['createDate'])),
        'lastUpdateDate': (new Date(json['lastUpdateDate'])),
        'createdBy': json['createdBy'],
    };
}

export function ItemAllOfToJSON(value?: ItemAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdBy': value.createdBy,
    };
}

