/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface ItemsGet200Response
 */
export interface ItemsGet200Response {
    /**
     * 
     * @type {Array<Item>}
     * @memberof ItemsGet200Response
     */
    rooms?: Array<Item>;
}

/**
 * Check if a given object implements the ItemsGet200Response interface.
 */
export function instanceOfItemsGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemsGet200ResponseFromJSON(json: any): ItemsGet200Response {
    return ItemsGet200ResponseFromJSONTyped(json, false);
}

export function ItemsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rooms': !exists(json, 'rooms') ? undefined : ((json['rooms'] as Array<any>).map(ItemFromJSON)),
    };
}

export function ItemsGet200ResponseToJSON(value?: ItemsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rooms': value.rooms === undefined ? undefined : ((value.rooms as Array<any>).map(ItemToJSON)),
    };
}

