/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * a group. this could be a project group, a team, or something else. this is sent by the client when creating a new group.
 * @export
 * @interface NewGroup
 */
export interface NewGroup {
    /**
     * the name of the group.
     * @type {string}
     * @memberof NewGroup
     */
    name: string;
}

/**
 * Check if a given object implements the NewGroup interface.
 */
export function instanceOfNewGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function NewGroupFromJSON(json: any): NewGroup {
    return NewGroupFromJSONTyped(json, false);
}

export function NewGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NewGroupToJSON(value?: NewGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

