/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * a recurring unavailability. this could be a maintenance window, a booking, or something else. the server will send this to clients
 * @export
 * @interface RecurringUnavailability
 */
export interface RecurringUnavailability {
    /**
     * the id of the item. 
     * @type {string}
     * @memberof RecurringUnavailability
     */
    item: string;
    /**
     * date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00
     * @type {string}
     * @memberof RecurringUnavailability
     */
    startDate: string;
    /**
     * date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00
     * @type {string}
     * @memberof RecurringUnavailability
     */
    endDate: string;
    /**
     * the id of the owner of the unavailability.
     * It can be a group or a user
     * @type {string}
     * @memberof RecurringUnavailability
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof RecurringUnavailability
     */
    type: RecurringUnavailabilityTypeEnum;
    /**
     * date-time string with 15-minute interval, e.g., 2023-04-02t12:00:00
     * @type {string}
     * @memberof RecurringUnavailability
     */
    recurrence: string;
    /**
     * the id of an unavailability.
     * @type {string}
     * @memberof RecurringUnavailability
     */
    id: string;
}


/**
 * @export
 */
export const RecurringUnavailabilityTypeEnum = {
    Maintenance: 'maintenance',
    Booking: 'booking',
    OffHours: 'offHours',
    Other: 'other'
} as const;
export type RecurringUnavailabilityTypeEnum = typeof RecurringUnavailabilityTypeEnum[keyof typeof RecurringUnavailabilityTypeEnum];


/**
 * Check if a given object implements the RecurringUnavailability interface.
 */
export function instanceOfRecurringUnavailability(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "item" in value;
    isInstance = isInstance && "startDate" in value;
    isInstance = isInstance && "endDate" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "recurrence" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function RecurringUnavailabilityFromJSON(json: any): RecurringUnavailability {
    return RecurringUnavailabilityFromJSONTyped(json, false);
}

export function RecurringUnavailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringUnavailability {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': json['item'],
        'startDate': json['startDate'],
        'endDate': json['endDate'],
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
        'type': json['type'],
        'recurrence': json['recurrence'],
        'id': json['id'],
    };
}

export function RecurringUnavailabilityToJSON(value?: RecurringUnavailability | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': value.item,
        'startDate': value.startDate,
        'endDate': value.endDate,
        'owner': value.owner,
        'type': value.type,
        'recurrence': value.recurrence,
        'id': value.id,
    };
}

