/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateUnavailability } from './UpdateUnavailability';
import {
    UpdateUnavailabilityFromJSON,
    UpdateUnavailabilityFromJSONTyped,
    UpdateUnavailabilityToJSON,
} from './UpdateUnavailability';

/**
 * 
 * @export
 * @interface UnavailabilitiesIdPut200Response
 */
export interface UnavailabilitiesIdPut200Response {
    /**
     * 
     * @type {UpdateUnavailability}
     * @memberof UnavailabilitiesIdPut200Response
     */
    booking?: UpdateUnavailability;
}

/**
 * Check if a given object implements the UnavailabilitiesIdPut200Response interface.
 */
export function instanceOfUnavailabilitiesIdPut200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UnavailabilitiesIdPut200ResponseFromJSON(json: any): UnavailabilitiesIdPut200Response {
    return UnavailabilitiesIdPut200ResponseFromJSONTyped(json, false);
}

export function UnavailabilitiesIdPut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnavailabilitiesIdPut200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'booking': !exists(json, 'booking') ? undefined : UpdateUnavailabilityFromJSON(json['booking']),
    };
}

export function UnavailabilitiesIdPut200ResponseToJSON(value?: UnavailabilitiesIdPut200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'booking': UpdateUnavailabilityToJSON(value.booking),
    };
}

