/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * a generic success response. it has a message property, which is a string.
 * @export
 * @interface UnavailabilitiesIdDelete200Response
 */
export interface UnavailabilitiesIdDelete200Response {
    /**
     * 
     * @type {string}
     * @memberof UnavailabilitiesIdDelete200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the UnavailabilitiesIdDelete200Response interface.
 */
export function instanceOfUnavailabilitiesIdDelete200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UnavailabilitiesIdDelete200ResponseFromJSON(json: any): UnavailabilitiesIdDelete200Response {
    return UnavailabilitiesIdDelete200ResponseFromJSONTyped(json, false);
}

export function UnavailabilitiesIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnavailabilitiesIdDelete200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function UnavailabilitiesIdDelete200ResponseToJSON(value?: UnavailabilitiesIdDelete200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

