/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnavailabilitiesPost400Response
 */
export interface UnavailabilitiesPost400Response {
    /**
     * 
     * @type {object}
     * @memberof UnavailabilitiesPost400Response
     */
    error?: object;
}

/**
 * Check if a given object implements the UnavailabilitiesPost400Response interface.
 */
export function instanceOfUnavailabilitiesPost400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UnavailabilitiesPost400ResponseFromJSON(json: any): UnavailabilitiesPost400Response {
    return UnavailabilitiesPost400ResponseFromJSONTyped(json, false);
}

export function UnavailabilitiesPost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnavailabilitiesPost400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function UnavailabilitiesPost400ResponseToJSON(value?: UnavailabilitiesPost400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

