/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * a group. this could be a project group, a team, or something else. this is sent by the client when updating an existing group.
 * @export
 * @interface UpdateGroup
 */
export interface UpdateGroup {
    /**
     * the name of the group.
     * @type {string}
     * @memberof UpdateGroup
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateGroup interface.
 */
export function instanceOfUpdateGroup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateGroupFromJSON(json: any): UpdateGroup {
    return UpdateGroupFromJSONTyped(json, false);
}

export function UpdateGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function UpdateGroupToJSON(value?: UpdateGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

