/* tslint:disable */
/* eslint-disable */
/**
 * Main API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * the user's id.
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * the user's picture URL
     * @type {string}
     * @memberof User
     */
    picture?: string;
    /**
     * the user's email.
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * the user's name.
     * @type {string}
     * @memberof User
     */
    name?: string;
    /**
     * the user's nickname.
     * @type {string}
     * @memberof User
     */
    nickname?: string;
    /**
     * the user's role.
     * @type {string}
     * @memberof User
     */
    role?: UserRoleEnum;
}


/**
 * @export
 */
export const UserRoleEnum = {
    Standard: 'standard',
    Staff: 'staff'
} as const;
export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];


/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'picture': value.picture,
        'email': value.email,
        'name': value.name,
        'nickname': value.nickname,
        'role': value.role,
    };
}

