# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class NewCredit(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NewCredit - a model defined in OpenAPI

        user_id: The user_id of this NewCredit.
        amount: The amount of this NewCredit.
    """

    user_id: int = Field(alias="user_id")
    amount: int = Field(alias="amount")

NewCredit.update_forward_refs()
