# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class UpdateCreditByIdRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UpdateCreditByIdRequest - a model defined in OpenAPI

        amount: The amount of this UpdateCreditByIdRequest.
    """

    amount: int = Field(alias="amount")

UpdateCreditByIdRequest.update_forward_refs()
