# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.update_unavailability import UpdateUnavailability


class UnavailabilitiesIdPut200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UnavailabilitiesIdPut200Response - a model defined in OpenAPI

        booking: The booking of this UnavailabilitiesIdPut200Response [Optional].
    """

    booking: Optional[Dict[str, Any]] = Field(alias="Booking", default=None)

UnavailabilitiesIdPut200Response.update_forward_refs()
