# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.unavailability import Unavailability


class UnavailabilitiesIdGet200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UnavailabilitiesIdGet200Response - a model defined in OpenAPI

        unavailability: The unavailability of this UnavailabilitiesIdGet200Response [Optional].
    """

    unavailability: Optional[Dict[str, Any]] = Field(alias="unavailability", default=None)

UnavailabilitiesIdGet200Response.update_forward_refs()
