# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.unavailability import Unavailability


class UnavailabilitiesGet200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UnavailabilitiesGet200Response - a model defined in OpenAPI

        unavailabilities: The unavailabilities of this UnavailabilitiesGet200Response [Optional].
    """

    unavailabilities: Optional[List[Unavailability]] = Field(alias="Unavailabilities", default=None)

UnavailabilitiesGet200Response.update_forward_refs()
