# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.group import Group


class GroupsGet200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GroupsGet200Response - a model defined in OpenAPI

        groups: The groups of this GroupsGet200Response [Optional].
    """

    groups: Optional[List[Group]] = Field(alias="Groups", default=None)

GroupsGet200Response.update_forward_refs()
